M48
; DRILL file {KiCad 8.0.5} date 2024-12-29T20:12:45-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-29T20:12:45-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X7.9224Y-3.5394
X7.9232Y-3.0118
X7.9724Y-3.5394
X7.9732Y-3.0118
M30
